//! The fact codec: commits to bytes and back, through `fact.proto` (ADR-0002, ADR-0032).
//!
//! A fact's kind and version are its `body` case (PRP-0006, option A), so a payload cannot be
//! filed under another kind. Encoding is deterministic: the same commit always yields the same
//! bytes. Decoding is bounded and strict. It never guesses: a store's format is checked when it
//! is opened, so every case and enum value of a store this build opens is one it knows, and an
//! unset case or an unknown value is a malformed commit naming its `seq` (`fact-format.md`,
//! § Reading old facts).

use std::collections::BTreeMap;

use prost::Message;
use yata_core::fact::{
    Commit, Digest, Fact, FactBody, Facts, GameAccountId, GameSoulId, Mark, NoteText, Origin,
    ProfileId, Sections, Seq, SnapshotImport,
};
use yata_core::import::ir::{Completeness, FormatTag, SchemaVersion, SectionKind, SourceFormat};

/// The fact schema, generated from `proto/fact.proto` at build time.
#[allow(
    clippy::all,
    clippy::pedantic,
    reason = "generated by prost from the schema file"
)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/yata.fact.v2.rs"));
}

/// The largest encoded commit this build writes or reads. Commits are facts, tens of bytes each;
/// a snapshot's bytes are a blob, not part of a commit.
pub const MAX_COMMIT_LEN: usize = 1 << 20;

/// What is wrong with a commit.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Malformation {
    NotACommit,
    NoOrigin,
    /// A commit holds at least one fact.
    NoFacts,
    /// The fact says what it is about in no case this build knows.
    NoSubject,
    ProfileIdLength,
    /// The fact is no case this build knows.
    NoBody,
    DigestLength,
    EmptySoulId,
    EmptyAccountId,
    /// An enum field holds its unspecified zero value.
    Unspecified(&'static str),
    /// An enum field holds a value this build does not know. A value is only added with a new
    /// store format, which this build would have refused.
    UnknownValue {
        field: &'static str,
        value: i32,
    },
    /// An import names its source format in no case this build knows.
    NoSource,
    /// An import holds no section.
    NoSections,
    /// An import lists a section twice.
    DuplicateSection,
    /// A note says neither a text nor that it is cleared.
    NoteUnset,
    /// A note gives an empty text; clearing is its own case.
    EmptyNoteText,
}

/// Why a commit could not be read back.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FactError {
    TooLarge {
        seq: Seq,
        len: usize,
    },
    Malformed {
        seq: Seq,
        what: Malformation,
    },
    /// The commit's own `seq` is not the row it was stored under.
    SeqMismatch {
        key: Seq,
        found: u64,
    },
}

/// Why a commit could not be written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EncodeError {
    TooLarge { len: usize },
}

/// Encode a commit.
pub fn encode_commit(commit: &Commit) -> Result<Vec<u8>, EncodeError> {
    let message = pb::Commit {
        seq: commit.seq.get(),
        recorded_at_unix_ms: commit.recorded_at_ms,
        origin: Some(pb::Origin {
            kind: Some(match commit.origin {
                Origin::Command { request_id } => pb::origin::Kind::CommandRequestId(request_id),
                Origin::Job { job_id } => pb::origin::Kind::JobId(job_id),
                Origin::Maintenance => pb::origin::Kind::Maintenance(pb::Maintenance {}),
            }),
        }),
        facts: commit.facts.as_slice().iter().map(encode_fact).collect(),
    };
    let bytes = message.encode_to_vec();
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(EncodeError::TooLarge { len: bytes.len() });
    }
    Ok(bytes)
}

fn encode_fact(fact: &Fact) -> pb::Fact {
    use pb::fact::Body;
    let body = match &fact.body {
        FactBody::ProfileCreated {
            display_name,
            account,
        } => Body::ProfileCreatedV1(pb::ProfileCreated {
            display_name: display_name.clone(),
            account_id: account.as_ref().map(|a| a.as_str().to_owned()),
        }),
        FactBody::ProfileRenamed { display_name } => Body::ProfileRenamedV1(pb::ProfileRenamed {
            display_name: display_name.clone(),
        }),
        FactBody::ProfileRetired => Body::ProfileRetiredV1(pb::ProfileRetired {}),
        FactBody::ProfileRestored => Body::ProfileRestoredV1(pb::ProfileRestored {}),
        FactBody::SnapshotImported(i) => Body::SnapshotImportedV1(encode_import(i)),
        FactBody::SnapshotRetracted { snapshot, reason } => {
            Body::SnapshotRetractedV1(pb::SnapshotRetracted {
                snapshot: snapshot.0.to_vec(),
                reason: reason.clone(),
            })
        }
        FactBody::SoulMarked { soul, mark } => Body::SoulMarkedV1(pb::SoulMarked {
            soul_id: soul.as_str().to_owned(),
            mark: match mark {
                None => pb::Mark::None,
                Some(Mark::Keep) => pb::Mark::Keep,
                Some(Mark::Discard) => pb::Mark::Discard,
                Some(Mark::Strengthen) => pb::Mark::Strengthen,
            }
            .into(),
        }),
        FactBody::SoulNoted { soul, note } => Body::SoulNotedV1(pb::SoulNoted {
            soul_id: soul.as_str().to_owned(),
            note: Some(match note {
                Some(text) => pb::soul_noted::Note::Text(text.as_str().to_owned()),
                None => pb::soul_noted::Note::Cleared(pb::NoteCleared {}),
            }),
        }),
    };
    pb::Fact {
        subject: Some(pb::fact::Subject::Profile(fact.profile.0.to_vec())),
        body: Some(body),
    }
}

fn encode_import(i: &SnapshotImport) -> pb::SnapshotImported {
    pb::SnapshotImported {
        snapshot: i.snapshot.0.to_vec(),
        original: i.original.0.to_vec(),
        source: Some(pb::SourceFormat {
            format: Some(match i.source {
                SourceFormat::YataSnapshot(v) => {
                    pb::source_format::Format::YataSnapshot(pb::SchemaVersion {
                        major: v.major,
                        minor: v.minor,
                    })
                }
                SourceFormat::Community(tag) => pb::source_format::Format::Community(
                    match tag {
                        FormatTag::MumuSnapshotV1 => pb::FormatTag::MumuSnapshotV1,
                    }
                    .into(),
                ),
            }),
        }),
        // A BTreeMap iterates in key order, so the encoding is deterministic.
        sections: i
            .sections
            .as_map()
            .iter()
            .map(|(k, c)| pb::SectionEntry {
                kind: section_kind(*k).into(),
                completeness: completeness(*c).into(),
            })
            .collect(),
    }
}

fn section_kind(k: SectionKind) -> pb::SectionKind {
    match k {
        SectionKind::Souls => pb::SectionKind::Souls,
        SectionKind::Shikigami => pb::SectionKind::Shikigami,
        SectionKind::Presets => pb::SectionKind::Presets,
        SectionKind::Assets => pb::SectionKind::Assets,
        SectionKind::Guild => pb::SectionKind::Guild,
    }
}

fn completeness(c: Completeness) -> pb::Completeness {
    match c {
        Completeness::Complete => pb::Completeness::Complete,
        Completeness::Partial => pb::Completeness::Partial,
        Completeness::Unstated => pb::Completeness::Unstated,
    }
}

/// Decode the commit stored under `key`.
pub fn decode_commit(key: Seq, bytes: &[u8]) -> Result<Commit, FactError> {
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(FactError::TooLarge {
            seq: key,
            len: bytes.len(),
        });
    }
    let malformed = |what| FactError::Malformed { seq: key, what };
    let message = pb::Commit::decode(bytes).map_err(|_| malformed(Malformation::NotACommit))?;
    if message.seq != key.get() {
        return Err(FactError::SeqMismatch {
            key,
            found: message.seq,
        });
    }
    let origin = match message.origin.and_then(|o| o.kind) {
        Some(pb::origin::Kind::CommandRequestId(request_id)) => Origin::Command { request_id },
        Some(pb::origin::Kind::JobId(job_id)) => Origin::Job { job_id },
        Some(pb::origin::Kind::Maintenance(_)) => Origin::Maintenance,
        None => return Err(malformed(Malformation::NoOrigin)),
    };
    let facts = message
        .facts
        .into_iter()
        .map(|f| decode_fact(f).map_err(malformed))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(Commit {
        seq: key,
        recorded_at_ms: message.recorded_at_unix_ms,
        origin,
        facts: Facts::new(facts).ok_or(malformed(Malformation::NoFacts))?,
    })
}

fn decode_fact(fact: pb::Fact) -> Result<Fact, Malformation> {
    use pb::fact::Body;
    let profile = match fact.subject {
        Some(pb::fact::Subject::Profile(id)) => <[u8; 16]>::try_from(id.as_slice())
            .map(ProfileId)
            .map_err(|_| Malformation::ProfileIdLength)?,
        None => return Err(Malformation::NoSubject),
    };
    let body = match fact.body.ok_or(Malformation::NoBody)? {
        Body::ProfileCreatedV1(p) => FactBody::ProfileCreated {
            display_name: p.display_name,
            account: p
                .account_id
                .map(GameAccountId::new)
                .transpose()
                .map_err(|_| Malformation::EmptyAccountId)?,
        },
        Body::ProfileRenamedV1(p) => FactBody::ProfileRenamed {
            display_name: p.display_name,
        },
        Body::ProfileRetiredV1(_) => FactBody::ProfileRetired,
        Body::ProfileRestoredV1(_) => FactBody::ProfileRestored,
        Body::SnapshotImportedV1(p) => FactBody::SnapshotImported(decode_import(p)?),
        Body::SnapshotRetractedV1(p) => FactBody::SnapshotRetracted {
            snapshot: digest(&p.snapshot)?,
            reason: p.reason,
        },
        Body::SoulMarkedV1(p) => FactBody::SoulMarked {
            soul: soul(p.soul_id)?,
            mark: match known::<pb::Mark>("mark", p.mark)? {
                pb::Mark::None => None,
                pb::Mark::Keep => Some(Mark::Keep),
                pb::Mark::Discard => Some(Mark::Discard),
                pb::Mark::Strengthen => Some(Mark::Strengthen),
                pb::Mark::Unspecified => return Err(Malformation::Unspecified("mark")),
            },
        },
        Body::SoulNotedV1(p) => FactBody::SoulNoted {
            soul: soul(p.soul_id)?,
            note: match p.note {
                Some(pb::soul_noted::Note::Text(text)) => {
                    Some(NoteText::new(text).ok_or(Malformation::EmptyNoteText)?)
                }
                Some(pb::soul_noted::Note::Cleared(_)) => None,
                None => return Err(Malformation::NoteUnset),
            },
        },
    };
    Ok(Fact { profile, body })
}

fn decode_import(p: pb::SnapshotImported) -> Result<SnapshotImport, Malformation> {
    let source = match p.source.and_then(|s| s.format) {
        Some(pb::source_format::Format::YataSnapshot(v)) => {
            SourceFormat::YataSnapshot(SchemaVersion {
                major: v.major,
                minor: v.minor,
            })
        }
        Some(pb::source_format::Format::Community(tag)) => {
            SourceFormat::Community(match known::<pb::FormatTag>("format_tag", tag)? {
                pb::FormatTag::MumuSnapshotV1 => FormatTag::MumuSnapshotV1,
                pb::FormatTag::Unspecified => return Err(Malformation::Unspecified("format_tag")),
            })
        }
        None => return Err(Malformation::NoSource),
    };
    let mut sections = BTreeMap::new();
    for e in p.sections {
        let kind = match known::<pb::SectionKind>("section_kind", e.kind)? {
            pb::SectionKind::Souls => SectionKind::Souls,
            pb::SectionKind::Shikigami => SectionKind::Shikigami,
            pb::SectionKind::Presets => SectionKind::Presets,
            pb::SectionKind::Assets => SectionKind::Assets,
            pb::SectionKind::Guild => SectionKind::Guild,
            pb::SectionKind::Unspecified => return Err(Malformation::Unspecified("section_kind")),
        };
        let c = match known::<pb::Completeness>("completeness", e.completeness)? {
            pb::Completeness::Complete => Completeness::Complete,
            pb::Completeness::Partial => Completeness::Partial,
            pb::Completeness::Unstated => Completeness::Unstated,
            pb::Completeness::Unspecified => return Err(Malformation::Unspecified("completeness")),
        };
        if sections.insert(kind, c).is_some() {
            return Err(Malformation::DuplicateSection);
        }
    }
    Ok(SnapshotImport {
        snapshot: digest(&p.snapshot)?,
        original: digest(&p.original)?,
        source,
        sections: Sections::new(sections).ok_or(Malformation::NoSections)?,
    })
}

fn known<E: TryFrom<i32>>(field: &'static str, value: i32) -> Result<E, Malformation> {
    E::try_from(value).map_err(|_| Malformation::UnknownValue { field, value })
}

fn digest(bytes: &[u8]) -> Result<Digest, Malformation> {
    <[u8; 32]>::try_from(bytes)
        .map(Digest)
        .map_err(|_| Malformation::DigestLength)
}

fn soul(id: String) -> Result<GameSoulId, Malformation> {
    GameSoulId::new(id).map_err(|_| Malformation::EmptySoulId)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::wire::Code as _;

    const P: ProfileId = ProfileId([0xAB; 16]);

    fn seq(n: u64) -> Seq {
        Seq::new(n).expect("a seq")
    }

    fn import() -> SnapshotImport {
        SnapshotImport {
            snapshot: Digest([7; 32]),
            original: Digest([8; 32]),
            source: SourceFormat::Community(FormatTag::MumuSnapshotV1),
            sections: Sections::new(BTreeMap::from([
                (SectionKind::Souls, Completeness::Complete),
                (SectionKind::Guild, Completeness::Unstated),
            ]))
            .expect("sections"),
        }
    }

    fn every_kind() -> Commit {
        let soul = GameSoulId::new("s-1").expect("non-empty");
        let facts = vec![
            FactBody::ProfileCreated {
                display_name: "主号".into(),
                account: Some(GameAccountId::new("acct").expect("non-empty")),
            },
            FactBody::ProfileRenamed {
                display_name: "alt".into(),
            },
            FactBody::ProfileRetired,
            FactBody::ProfileRestored,
            FactBody::SnapshotImported(import()),
            FactBody::SnapshotImported(SnapshotImport {
                source: SourceFormat::YataSnapshot(SchemaVersion { major: 1, minor: 2 }),
                ..import()
            }),
            FactBody::SnapshotRetracted {
                snapshot: Digest([7; 32]),
                reason: "wrong account".into(),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: Some(Mark::Strengthen),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: None,
            },
            FactBody::SoulNoted {
                soul: soul.clone(),
                note: NoteText::new("双速"),
            },
            FactBody::SoulNoted { soul, note: None },
        ];
        Commit {
            seq: seq(3),
            recorded_at_ms: -5,
            origin: Origin::Job { job_id: 9 },
            facts: Facts::new(
                facts
                    .into_iter()
                    .map(|body| Fact { profile: P, body })
                    .collect(),
            )
            .expect("facts"),
        }
    }

    fn raw(commit: &Commit) -> pb::Commit {
        pb::Commit::decode(encode_commit(commit).expect("encodes").as_slice()).expect("decodes")
    }

    /// `every_kind`, with its import fact (the fifth) changed.
    fn with_import(f: impl FnOnce(&mut pb::SnapshotImported)) -> Vec<u8> {
        let mut c = raw(&every_kind());
        let Some(pb::fact::Body::SnapshotImportedV1(i)) = &mut c.facts[4].body else {
            panic!("the fifth fact is an import");
        };
        f(i);
        c.encode_to_vec()
    }

    fn with_fact(f: impl FnOnce(&mut pb::Fact)) -> Vec<u8> {
        let mut c = raw(&every_kind());
        f(&mut c.facts[0]);
        c.encode_to_vec()
    }

    fn malformed(what: Malformation) -> Result<Commit, FactError> {
        Err(FactError::Malformed { seq: seq(3), what })
    }

    #[test]
    fn every_kind_round_trips() {
        let c = every_kind();
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(decode_commit(seq(3), &bytes), Ok(c));
    }

    #[test]
    fn every_origin_round_trips() {
        for origin in [
            Origin::Command { request_id: 1 },
            Origin::Job { job_id: 2 },
            Origin::Maintenance,
        ] {
            let c = Commit {
                origin,
                ..every_kind()
            };
            let bytes = encode_commit(&c).expect("encodes");
            assert_eq!(decode_commit(seq(3), &bytes).map(|d| d.origin), Ok(origin));
        }
    }

    #[test]
    fn encoding_is_deterministic_and_pinned() {
        let c = Commit {
            seq: seq(1),
            recorded_at_ms: 0,
            origin: Origin::Command { request_id: 1 },
            facts: Facts::one(Fact {
                profile: ProfileId([0; 16]),
                body: FactBody::SoulMarked {
                    soul: GameSoulId::new("a").expect("non-empty"),
                    mark: Some(Mark::Keep),
                },
            }),
        };
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(encode_commit(&c), Ok(bytes.clone()));
        let decoded = decode_commit(seq(1), &bytes).expect("decodes");
        assert_eq!(encode_commit(&decoded), Ok(bytes.clone()));
        // These bytes are what every format-2 store holds for this commit; a change here breaks
        // stores.
        let pinned: &[u8] = &[
            0x08, 0x01, // seq 1
            0x1A, 0x02, 0x08, 0x01, // origin: command request id 1
            0x22, 0x1A, // fact, 26 bytes
            0x0A, 0x10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // subject: profile
            0x82, 0x01, 0x05, 0x0A, 0x01, b'a', 0x10, 0x02, // body 16: soul "a", mark Keep
        ];
        assert_eq!(bytes, pinned);
    }

    #[test]
    fn an_import_lists_its_sections_in_kind_order() {
        let c = raw(&every_kind());
        let Some(pb::fact::Body::SnapshotImportedV1(i)) = &c.facts[4].body else {
            panic!("an import");
        };
        let kinds: Vec<i32> = i.sections.iter().map(|e| e.kind).collect();
        assert_eq!(
            kinds,
            vec![
                i32::from(pb::SectionKind::Souls),
                i32::from(pb::SectionKind::Guild)
            ]
        );
    }

    #[test]
    fn a_note_must_say_which_case_it_is() {
        let note = |n| {
            with_fact(|f| {
                f.body = Some(pb::fact::Body::SoulNotedV1(pb::SoulNoted {
                    soul_id: "s".into(),
                    note: n,
                }));
            })
        };
        assert_eq!(
            decode_commit(seq(3), &note(None)),
            malformed(Malformation::NoteUnset)
        );
        assert_eq!(
            decode_commit(
                seq(3),
                &note(Some(pb::soul_noted::Note::Text(String::new())))
            ),
            malformed(Malformation::EmptyNoteText)
        );
    }

    #[test]
    fn bytes_that_are_not_a_commit_are_malformed() {
        assert_eq!(
            decode_commit(seq(1), &[0xFF, 0xFF, 0xFF]),
            Err(FactError::Malformed {
                seq: seq(1),
                what: Malformation::NotACommit
            })
        );
        let no_origin = pb::Commit {
            seq: 1,
            ..pb::Commit::default()
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(seq(1), &no_origin),
            Err(FactError::Malformed {
                seq: seq(1),
                what: Malformation::NoOrigin
            })
        );
        let no_facts = pb::Commit {
            facts: vec![],
            ..raw(&every_kind())
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(seq(3), &no_facts),
            malformed(Malformation::NoFacts)
        );
    }

    #[test]
    fn a_commit_must_sit_under_its_own_seq() {
        let bytes = encode_commit(&every_kind()).expect("encodes");
        assert_eq!(
            decode_commit(seq(4), &bytes),
            Err(FactError::SeqMismatch {
                key: seq(4),
                found: 3
            })
        );
    }

    #[test]
    fn decoding_is_bounded() {
        let big = vec![0u8; MAX_COMMIT_LEN + 1];
        assert_eq!(
            decode_commit(seq(1), &big),
            Err(FactError::TooLarge {
                seq: seq(1),
                len: MAX_COMMIT_LEN + 1
            })
        );
        let c = Commit {
            facts: Facts::one(Fact {
                profile: P,
                body: FactBody::SoulNoted {
                    soul: GameSoulId::new("a").expect("non-empty"),
                    note: NoteText::new("x".repeat(MAX_COMMIT_LEN)),
                },
            }),
            ..every_kind()
        };
        assert!(matches!(
            encode_commit(&c),
            Err(EncodeError::TooLarge { .. })
        ));
    }

    #[test]
    fn a_fact_is_about_a_profile_and_is_some_case() {
        assert_eq!(
            decode_commit(seq(3), &with_fact(|f| f.subject = None)),
            malformed(Malformation::NoSubject)
        );
        assert_eq!(
            decode_commit(
                seq(3),
                &with_fact(|f| f.subject = Some(pb::fact::Subject::Profile(vec![1; 15])))
            ),
            malformed(Malformation::ProfileIdLength)
        );
        // A case this build does not know decodes as no case at all: in a store of a format it
        // opened, that is a broken commit, never a newer one (ADR-0032, rule 2).
        let mut fact = pb::Fact {
            subject: Some(pb::fact::Subject::Profile(P.0.to_vec())),
            body: None,
        }
        .encode_to_vec();
        fact.extend([0x9A, 0x06, 0x00]); // field 99, empty: a case of a newer schema
        let mut unknown_case = pb::Commit {
            facts: vec![],
            ..raw(&every_kind())
        }
        .encode_to_vec();
        unknown_case.extend([0x22, u8::try_from(fact.len()).expect("short")]);
        unknown_case.extend(fact);
        let e = decode_commit(seq(3), &unknown_case);
        assert_eq!(e, malformed(Malformation::NoBody));
        assert_eq!(
            e.map_err(|e| crate::wire::fact_failure(&e).code()),
            Err("store.malformed_commit")
        );
    }

    #[test]
    fn an_import_states_its_digests_source_and_sections_once_each() {
        let cases: [(Malformation, Vec<u8>); 7] = [
            (
                Malformation::DigestLength,
                with_import(|i| i.snapshot = vec![0; 31]),
            ),
            (
                Malformation::DigestLength,
                with_import(|i| i.original = vec![]),
            ),
            (Malformation::NoSource, with_import(|i| i.source = None)),
            (
                Malformation::NoSections,
                with_import(|i| i.sections.clear()),
            ),
            (
                Malformation::DuplicateSection,
                with_import(|i| {
                    let first = i.sections[0];
                    i.sections.push(first);
                }),
            ),
            (
                Malformation::Unspecified("completeness"),
                with_import(|i| i.sections[0].completeness = 0),
            ),
            (
                Malformation::UnknownValue {
                    field: "section_kind",
                    value: 42,
                },
                with_import(|i| i.sections[0].kind = 42),
            ),
        ];
        for (what, bytes) in cases {
            let e = decode_commit(seq(3), &bytes);
            assert_eq!(e, malformed(what), "{what:?}");
            assert_eq!(
                e.map_err(|e| crate::wire::fact_failure(&e).code()),
                Err("store.malformed_commit"),
                "{what:?}"
            );
        }
    }

    #[test]
    fn a_malformed_payload_is_refused() {
        let created_empty_account = with_fact(|f| {
            f.body = Some(pb::fact::Body::ProfileCreatedV1(pb::ProfileCreated {
                display_name: "x".into(),
                account_id: Some(String::new()),
            }));
        });
        assert_eq!(
            decode_commit(seq(3), &created_empty_account),
            malformed(Malformation::EmptyAccountId)
        );
        let unknown_mark = with_fact(|f| {
            f.body = Some(pb::fact::Body::SoulMarkedV1(pb::SoulMarked {
                soul_id: "s".into(),
                mark: 42,
            }));
        });
        assert_eq!(
            decode_commit(seq(3), &unknown_mark),
            malformed(Malformation::UnknownValue {
                field: "mark",
                value: 42
            })
        );
        let empty_soul = with_fact(|f| {
            f.body = Some(pb::fact::Body::SoulMarkedV1(pb::SoulMarked {
                soul_id: String::new(),
                mark: pb::Mark::Keep.into(),
            }));
        });
        assert_eq!(
            decode_commit(seq(3), &empty_soul),
            malformed(Malformation::EmptySoulId)
        );
    }
}
