//! The fact codec: commits to bytes and back, through `fact.proto` (ADR-0002).
//!
//! Encoding is deterministic: the same commit always yields the same bytes. Decoding is bounded
//! and strict, and lifts every payload to its kind's current form. It never guesses: a payload it
//! cannot read is an error naming the commit's `seq`, and a payload written by a newer build is
//! `store.newer_format` (`fact-format.md`, § Reading old facts).

use prost::Message;
use yata_core::fact::{
    Acquisition, Channel, Commit, Coverage, Digest, Fact, FactBody, GameAccountId, GameSoulId,
    Mark, Origin, ProbeVersion, ProfileId, Scope, Source,
};

/// The fact schema, generated from `proto/fact.proto` at build time.
#[allow(
    clippy::all,
    clippy::pedantic,
    reason = "generated by prost from the schema file"
)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/yata.fact.v1.rs"));
}

/// The largest encoded commit this build writes or reads. Commits are facts, tens of bytes each;
/// a reading's bytes are a blob, not part of a commit.
pub const MAX_COMMIT_LEN: usize = 1 << 20;

/// Every kind implemented so far is at version 1. A kind's version moves only when its meaning
/// changes, and each move adds a step to [`lift`].
const CURRENT_VERSION: u32 = 1;

/// A payload written by a newer build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Newer {
    Kind(i32),
    KindVersion {
        kind: &'static str,
        version: u32,
    },
    /// An enum value is only ever added, by a newer build; this one is unknown here.
    EnumValue {
        field: &'static str,
        value: i32,
    },
}

/// Why a commit could not be read back.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FactError {
    TooLarge {
        seq: u64,
        len: usize,
    },
    Malformed {
        seq: u64,
        detail: &'static str,
    },
    /// The commit's own `seq` is not the row it was stored under.
    SeqMismatch {
        key: u64,
        found: u64,
    },
    NewerFormat {
        seq: u64,
        what: Newer,
    },
}

impl FactError {
    /// The stable error code (`core-protocol.md`, § Errors).
    pub fn code(&self) -> &'static str {
        match self {
            FactError::NewerFormat { .. } => "store.newer_format",
            FactError::TooLarge { .. }
            | FactError::Malformed { .. }
            | FactError::SeqMismatch { .. } => "store.malformed_commit",
        }
    }
}

/// Why a commit could not be written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EncodeError {
    TooLarge { len: usize },
}

/// Encode a commit. Every fact is written at its kind's current version.
pub fn encode_commit(commit: &Commit) -> Result<Vec<u8>, EncodeError> {
    let message = pb::Commit {
        seq: commit.seq,
        recorded_at_unix_ms: commit.recorded_at_ms,
        origin: Some(pb::Origin {
            kind: Some(match commit.origin {
                Origin::Command { request_id } => pb::origin::Kind::CommandRequestId(request_id),
                Origin::Job { job_id } => pb::origin::Kind::JobId(job_id),
                Origin::Maintenance => pb::origin::Kind::Maintenance(pb::Maintenance {}),
            }),
        }),
        facts: commit.facts.iter().map(encode_fact).collect(),
    };
    let bytes = message.encode_to_vec();
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(EncodeError::TooLarge { len: bytes.len() });
    }
    Ok(bytes)
}

fn encode_fact(fact: &Fact) -> pb::Fact {
    let (kind, payload) = match &fact.body {
        FactBody::ProfileCreated {
            display_name,
            account,
        } => (
            pb::FactKind::ProfileCreated,
            pb::ProfileCreated {
                display_name: display_name.clone(),
                observed_account_id: account.as_ref().map(|a| a.as_str().to_owned()),
            }
            .encode_to_vec(),
        ),
        FactBody::ProfileRenamed { display_name } => (
            pb::FactKind::ProfileRenamed,
            pb::ProfileRenamed {
                display_name: display_name.clone(),
            }
            .encode_to_vec(),
        ),
        FactBody::ProfileRetired => (
            pb::FactKind::ProfileRetired,
            pb::ProfileRetired {}.encode_to_vec(),
        ),
        FactBody::ProfileRestored => (
            pb::FactKind::ProfileRestored,
            pb::ProfileRestored {}.encode_to_vec(),
        ),
        FactBody::SnapshotAcquired(a) => (
            pb::FactKind::SnapshotAcquired,
            encode_acquisition(a).encode_to_vec(),
        ),
        FactBody::SnapshotRetracted { digest, reason } => (
            pb::FactKind::SnapshotRetracted,
            pb::SnapshotRetracted {
                digest: digest.to_vec(),
                reason: reason.clone(),
            }
            .encode_to_vec(),
        ),
        FactBody::SoulMarked { soul, mark } => (
            pb::FactKind::SoulMarked,
            pb::SoulMarked {
                soul_id: soul.as_str().to_owned(),
                mark: match mark {
                    None => pb::Mark::None,
                    Some(Mark::Keep) => pb::Mark::Keep,
                    Some(Mark::Discard) => pb::Mark::Discard,
                    Some(Mark::Strengthen) => pb::Mark::Strengthen,
                }
                .into(),
            }
            .encode_to_vec(),
        ),
        FactBody::SoulNoted { soul, text } => (
            pb::FactKind::SoulNoted,
            pb::SoulNoted {
                soul_id: soul.as_str().to_owned(),
                text: text.clone(),
            }
            .encode_to_vec(),
        ),
    };
    pb::Fact {
        profile: fact.profile.0.to_vec(),
        kind: kind.into(),
        version: CURRENT_VERSION,
        payload,
    }
}

fn encode_acquisition(a: &Acquisition) -> pb::SnapshotAcquired {
    pb::SnapshotAcquired {
        digest: a.digest.to_vec(),
        scope: match a.scope {
            Scope::Souls => pb::Scope::Souls,
        }
        .into(),
        coverage: match a.coverage {
            Coverage::Complete => pb::Coverage::Complete,
            Coverage::Partial => pb::Coverage::Partial,
        }
        .into(),
        channel: match a.channel {
            Channel::DesktopMemory => pb::Channel::DesktopMemory,
            Channel::MumuAdb => pb::Channel::MumuAdb,
        }
        .into(),
        source: match a.source {
            Source::Live => pb::Source::Live,
            Source::ExportFile => pb::Source::ExportFile,
        }
        .into(),
        probe_build_id: a.probe_build_id.clone(),
        probe_protocol_major: a.probe_version.major,
        probe_protocol_minor: a.probe_version.minor,
        observed_account_id: a.observed_account.as_ref().map(|id| id.as_str().to_owned()),
    }
}

/// Decode the commit stored under `key`, lifting every fact to its current form.
pub fn decode_commit(key: u64, bytes: &[u8]) -> Result<Commit, FactError> {
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(FactError::TooLarge {
            seq: key,
            len: bytes.len(),
        });
    }
    let malformed = |detail| FactError::Malformed { seq: key, detail };
    let message = pb::Commit::decode(bytes).map_err(|_| malformed("not a commit"))?;
    if message.seq != key {
        return Err(FactError::SeqMismatch {
            key,
            found: message.seq,
        });
    }
    let origin = match message.origin.and_then(|o| o.kind) {
        Some(pb::origin::Kind::CommandRequestId(request_id)) => Origin::Command { request_id },
        Some(pb::origin::Kind::JobId(job_id)) => Origin::Job { job_id },
        Some(pb::origin::Kind::Maintenance(_)) => Origin::Maintenance,
        None => return Err(malformed("no origin")),
    };
    let facts = message
        .facts
        .iter()
        .map(|f| decode_fact(key, f))
        .collect::<Result<_, _>>()?;
    Ok(Commit {
        seq: key,
        recorded_at_ms: message.recorded_at_unix_ms,
        origin,
        facts,
    })
}

fn decode_fact(seq: u64, fact: &pb::Fact) -> Result<Fact, FactError> {
    let malformed = |detail| FactError::Malformed { seq, detail };
    let profile = <[u8; 16]>::try_from(fact.profile.as_slice())
        .map(ProfileId)
        .map_err(|_| malformed("profile id is not 16 bytes"))?;
    let kind = pb::FactKind::try_from(fact.kind).map_err(|_| FactError::NewerFormat {
        seq,
        what: Newer::Kind(fact.kind),
    })?;
    if kind == pb::FactKind::Unspecified {
        return Err(malformed("fact kind unspecified"));
    }
    if fact.version == 0 {
        return Err(malformed("fact version 0"));
    }
    if fact.version > CURRENT_VERSION {
        return Err(FactError::NewerFormat {
            seq,
            what: Newer::KindVersion {
                kind: kind.as_str_name(),
                version: fact.version,
            },
        });
    }
    let body = lift(seq, kind, fact.version, &fact.payload)?;
    Ok(Fact { profile, body })
}

/// `lift : (kind, version, payload) → current payload of that kind` (`fact-format.md`). Every
/// kind is at version 1, so the chain has no steps yet; a meaning change adds one here and
/// never removes one, because a version-1 fact may be in any store forever.
fn lift(seq: u64, kind: pb::FactKind, version: u32, payload: &[u8]) -> Result<FactBody, FactError> {
    debug_assert_eq!(version, CURRENT_VERSION);
    let malformed = |detail| FactError::Malformed { seq, detail };
    let bad = |_| malformed("payload does not decode as its kind");
    Ok(match kind {
        pb::FactKind::Unspecified => return Err(malformed("fact kind unspecified")),
        pb::FactKind::ProfileCreated => {
            let p = pb::ProfileCreated::decode(payload).map_err(bad)?;
            FactBody::ProfileCreated {
                display_name: p.display_name,
                account: account(seq, p.observed_account_id)?,
            }
        }
        pb::FactKind::ProfileRenamed => {
            let p = pb::ProfileRenamed::decode(payload).map_err(bad)?;
            FactBody::ProfileRenamed {
                display_name: p.display_name,
            }
        }
        pb::FactKind::ProfileRetired => {
            pb::ProfileRetired::decode(payload).map_err(bad)?;
            FactBody::ProfileRetired
        }
        pb::FactKind::ProfileRestored => {
            pb::ProfileRestored::decode(payload).map_err(bad)?;
            FactBody::ProfileRestored
        }
        pb::FactKind::SnapshotAcquired => {
            let p = pb::SnapshotAcquired::decode(payload).map_err(bad)?;
            FactBody::SnapshotAcquired(decode_acquisition(seq, p)?)
        }
        pb::FactKind::SnapshotRetracted => {
            let p = pb::SnapshotRetracted::decode(payload).map_err(bad)?;
            FactBody::SnapshotRetracted {
                digest: digest(seq, &p.digest)?,
                reason: p.reason,
            }
        }
        pb::FactKind::SoulMarked => {
            let p = pb::SoulMarked::decode(payload).map_err(bad)?;
            let mark = match known::<pb::Mark>(seq, "mark", p.mark)? {
                pb::Mark::None => None,
                pb::Mark::Keep => Some(Mark::Keep),
                pb::Mark::Discard => Some(Mark::Discard),
                pb::Mark::Strengthen => Some(Mark::Strengthen),
                pb::Mark::Unspecified => return Err(malformed("mark unspecified")),
            };
            FactBody::SoulMarked {
                soul: soul(seq, p.soul_id)?,
                mark,
            }
        }
        pb::FactKind::SoulNoted => {
            let p = pb::SoulNoted::decode(payload).map_err(bad)?;
            FactBody::SoulNoted {
                soul: soul(seq, p.soul_id)?,
                text: p.text,
            }
        }
    })
}

fn decode_acquisition(seq: u64, p: pb::SnapshotAcquired) -> Result<Acquisition, FactError> {
    let unspecified = |field| FactError::Malformed { seq, detail: field };
    Ok(Acquisition {
        digest: digest(seq, &p.digest)?,
        scope: match known::<pb::Scope>(seq, "scope", p.scope)? {
            pb::Scope::Souls => Scope::Souls,
            pb::Scope::Unspecified => return Err(unspecified("scope unspecified")),
        },
        coverage: match known::<pb::Coverage>(seq, "coverage", p.coverage)? {
            pb::Coverage::Complete => Coverage::Complete,
            pb::Coverage::Partial => Coverage::Partial,
            pb::Coverage::Unspecified => return Err(unspecified("coverage unspecified")),
        },
        channel: match known::<pb::Channel>(seq, "channel", p.channel)? {
            pb::Channel::DesktopMemory => Channel::DesktopMemory,
            pb::Channel::MumuAdb => Channel::MumuAdb,
            pb::Channel::Unspecified => return Err(unspecified("channel unspecified")),
        },
        source: match known::<pb::Source>(seq, "source", p.source)? {
            pb::Source::Live => Source::Live,
            pb::Source::ExportFile => Source::ExportFile,
            pb::Source::Unspecified => return Err(unspecified("source unspecified")),
        },
        probe_build_id: p.probe_build_id,
        probe_version: ProbeVersion {
            major: p.probe_protocol_major,
            minor: p.probe_protocol_minor,
        },
        observed_account: account(seq, p.observed_account_id)?,
    })
}

fn known<E: TryFrom<i32>>(seq: u64, field: &'static str, value: i32) -> Result<E, FactError> {
    E::try_from(value).map_err(|_| FactError::NewerFormat {
        seq,
        what: Newer::EnumValue { field, value },
    })
}

fn digest(seq: u64, bytes: &[u8]) -> Result<Digest, FactError> {
    Digest::try_from(bytes).map_err(|_| FactError::Malformed {
        seq,
        detail: "digest is not 32 bytes",
    })
}

fn soul(seq: u64, id: String) -> Result<GameSoulId, FactError> {
    GameSoulId::new(id).map_err(|_| FactError::Malformed {
        seq,
        detail: "empty soul id",
    })
}

fn account(seq: u64, id: Option<String>) -> Result<Option<GameAccountId>, FactError> {
    id.map(GameAccountId::new)
        .transpose()
        .map_err(|_| FactError::Malformed {
            seq,
            detail: "empty account id",
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    const P: ProfileId = ProfileId([0xAB; 16]);

    fn every_kind() -> Commit {
        let soul = GameSoulId::new("s-1").expect("non-empty");
        let facts = vec![
            FactBody::ProfileCreated {
                display_name: "主号".into(),
                account: Some(GameAccountId::new("acct").expect("non-empty")),
            },
            FactBody::ProfileRenamed {
                display_name: "alt".into(),
            },
            FactBody::ProfileRetired,
            FactBody::ProfileRestored,
            FactBody::SnapshotAcquired(Acquisition {
                digest: [7; 32],
                scope: Scope::Souls,
                coverage: Coverage::Partial,
                channel: Channel::DesktopMemory,
                source: Source::Live,
                probe_build_id: "probe-1".into(),
                probe_version: ProbeVersion { major: 1, minor: 2 },
                observed_account: None,
            }),
            FactBody::SnapshotRetracted {
                digest: [7; 32],
                reason: "wrong account".into(),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: Some(Mark::Strengthen),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: None,
            },
            FactBody::SoulNoted {
                soul,
                text: "双速".into(),
            },
        ];
        Commit {
            seq: 3,
            recorded_at_ms: -5,
            origin: Origin::Job { job_id: 9 },
            facts: facts
                .into_iter()
                .map(|body| Fact { profile: P, body })
                .collect(),
        }
    }

    fn raw(commit: &Commit) -> pb::Commit {
        pb::Commit::decode(encode_commit(commit).expect("encodes").as_slice()).expect("decodes")
    }

    fn with_fact(f: impl FnOnce(&mut pb::Fact)) -> Vec<u8> {
        let mut c = raw(&every_kind());
        f(&mut c.facts[0]);
        c.encode_to_vec()
    }

    #[test]
    fn every_kind_round_trips() {
        let c = every_kind();
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(decode_commit(3, &bytes), Ok(c));
    }

    #[test]
    fn every_origin_round_trips() {
        for origin in [
            Origin::Command { request_id: 1 },
            Origin::Job { job_id: 2 },
            Origin::Maintenance,
        ] {
            let c = Commit {
                origin,
                ..every_kind()
            };
            let bytes = encode_commit(&c).expect("encodes");
            assert_eq!(decode_commit(3, &bytes).map(|d| d.origin), Ok(origin));
        }
    }

    #[test]
    fn encoding_is_deterministic_and_pinned() {
        let c = Commit {
            seq: 1,
            recorded_at_ms: 0,
            origin: Origin::Command { request_id: 1 },
            facts: vec![Fact {
                profile: ProfileId([0; 16]),
                body: FactBody::SoulMarked {
                    soul: GameSoulId::new("a").expect("non-empty"),
                    mark: Some(Mark::Keep),
                },
            }],
        };
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(encode_commit(&c), Ok(bytes.clone()));
        let decoded = decode_commit(1, &bytes).expect("decodes");
        assert_eq!(encode_commit(&decoded), Ok(bytes.clone()));
        // These bytes are what every store holds for this commit; a change here breaks stores.
        let pinned: &[u8] = &[
            0x08, 0x01, // seq 1
            0x1A, 0x02, 0x08, 0x01, // origin: command request id 1
            0x22, 0x1D, // fact, 29 bytes
            0x0A, 0x10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // profile
            0x10, 0x07, // kind SoulMarked
            0x18, 0x01, // version 1
            0x22, 0x05, 0x0A, 0x01, b'a', 0x10, 0x02, // payload: soul "a", mark Keep
        ];
        assert_eq!(bytes, pinned);
    }

    #[test]
    fn bytes_that_are_not_a_commit_are_malformed() {
        assert!(matches!(
            decode_commit(1, &[0xFF, 0xFF, 0xFF]),
            Err(FactError::Malformed { seq: 1, .. })
        ));
        let no_origin = pb::Commit {
            seq: 1,
            ..pb::Commit::default()
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(1, &no_origin),
            Err(FactError::Malformed {
                seq: 1,
                detail: "no origin"
            })
        );
    }

    #[test]
    fn a_commit_must_sit_under_its_own_seq() {
        let bytes = encode_commit(&every_kind()).expect("encodes");
        assert_eq!(
            decode_commit(4, &bytes),
            Err(FactError::SeqMismatch { key: 4, found: 3 })
        );
    }

    #[test]
    fn decoding_is_bounded() {
        let big = vec![0u8; MAX_COMMIT_LEN + 1];
        assert_eq!(
            decode_commit(1, &big),
            Err(FactError::TooLarge {
                seq: 1,
                len: MAX_COMMIT_LEN + 1
            })
        );
        let mut c = every_kind();
        c.facts[0].body = FactBody::SoulNoted {
            soul: GameSoulId::new("a").expect("non-empty"),
            text: "x".repeat(MAX_COMMIT_LEN),
        };
        assert!(matches!(
            encode_commit(&c),
            Err(EncodeError::TooLarge { .. })
        ));
    }

    #[test]
    fn a_newer_kind_version_or_enum_value_is_newer_format() {
        let unknown_kind = with_fact(|f| f.kind = 99);
        assert_eq!(
            decode_commit(3, &unknown_kind),
            Err(FactError::NewerFormat {
                seq: 3,
                what: Newer::Kind(99)
            })
        );
        let v2 = with_fact(|f| f.version = 2);
        let e = decode_commit(3, &v2).expect_err("newer");
        assert_eq!(e.code(), "store.newer_format");
        assert!(matches!(
            e,
            FactError::NewerFormat {
                what: Newer::KindVersion { version: 2, .. },
                ..
            }
        ));
        let mut c = raw(&every_kind());
        c.facts[6].payload = pb::SoulMarked {
            soul_id: "s".into(),
            mark: 42,
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(3, &c.encode_to_vec()),
            Err(FactError::NewerFormat {
                seq: 3,
                what: Newer::EnumValue {
                    field: "mark",
                    value: 42
                }
            })
        );
    }

    #[test]
    fn a_malformed_envelope_or_payload_is_refused() {
        let cases: [(&str, Vec<u8>); 6] = [
            ("fact version 0", with_fact(|f| f.version = 0)),
            ("fact kind unspecified", with_fact(|f| f.kind = 0)),
            (
                "profile id is not 16 bytes",
                with_fact(|f| f.profile = vec![1; 15]),
            ),
            (
                "payload does not decode as its kind",
                with_fact(|f| f.payload = vec![0x0A, 0x05, b'x']),
            ),
            (
                "empty account id",
                with_fact(|f| {
                    f.payload = pb::ProfileCreated {
                        display_name: "x".into(),
                        observed_account_id: Some(String::new()),
                    }
                    .encode_to_vec();
                }),
            ),
            (
                "coverage unspecified",
                with_fact(|f| {
                    f.kind = pb::FactKind::SnapshotAcquired.into();
                    f.payload = pb::SnapshotAcquired {
                        digest: vec![0; 32],
                        scope: pb::Scope::Souls.into(),
                        channel: pb::Channel::MumuAdb.into(),
                        source: pb::Source::Live.into(),
                        ..pb::SnapshotAcquired::default()
                    }
                    .encode_to_vec();
                }),
            ),
        ];
        for (detail, bytes) in cases {
            let e = decode_commit(3, &bytes).expect_err(detail);
            assert_eq!(e, FactError::Malformed { seq: 3, detail }, "{detail}");
            assert_eq!(e.code(), "store.malformed_commit");
        }
    }
}
