//! The fact codec: commits to bytes and back, through `fact.proto` (ADR-0002).
//!
//! Encoding is deterministic: the same commit always yields the same bytes. Decoding is bounded
//! and strict, and lifts every payload to its kind's current form. It never guesses: a payload it
//! cannot read is an error naming the commit's `seq`, and a payload written by a newer build is
//! `store.newer_format` (`fact-format.md`, § Reading old facts).

use prost::Message;
use yata_core::fact::{
    Acquisition, Channel, Commit, Coverage, Digest, Fact, FactBody, Facts, GameAccountId,
    GameSoulId, Mark, NoteText, Origin, ProbeVersion, ProfileId, Scope, Seq, Source,
};

/// The fact schema, generated from `proto/fact.proto` at build time.
#[allow(
    clippy::all,
    clippy::pedantic,
    reason = "generated by prost from the schema file"
)]
mod pb {
    include!(concat!(env!("OUT_DIR"), "/yata.fact.v1.rs"));
}

/// The largest encoded commit this build writes or reads. Commits are facts, tens of bytes each;
/// a reading's bytes are a blob, not part of a commit.
pub const MAX_COMMIT_LEN: usize = 1 << 20;

/// The version this build writes of each kind. A kind's version moves only when its meaning
/// changes, and each move adds a step to [`lift`].
fn current_version(kind: pb::FactKind) -> u32 {
    match kind {
        pb::FactKind::SoulNoted => 2,
        pb::FactKind::Unspecified
        | pb::FactKind::ProfileCreated
        | pb::FactKind::ProfileRenamed
        | pb::FactKind::ProfileRetired
        | pb::FactKind::ProfileRestored
        | pb::FactKind::SnapshotAcquired
        | pb::FactKind::SnapshotRetracted
        | pb::FactKind::SoulMarked => 1,
    }
}

/// A payload written by a newer build.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Newer {
    Kind(i32),
    KindVersion {
        kind: &'static str,
        version: u32,
    },
    /// An enum value is only ever added, by a newer build; this one is unknown here.
    EnumValue {
        field: &'static str,
        value: i32,
    },
}

/// What is wrong with a commit that is not newer than this build, only broken.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Malformation {
    NotACommit,
    NoOrigin,
    /// A commit holds at least one fact.
    NoFacts,
    ProfileIdLength,
    KindUnspecified,
    VersionZero,
    PayloadUndecodable,
    DigestLength,
    EmptySoulId,
    EmptyAccountId,
    /// An enum field holds its unspecified zero value.
    Unspecified(&'static str),
    /// A version-2 note says neither a text nor that it is cleared.
    NoteUnset,
    /// A version-2 note gives an empty text; clearing is its own case.
    EmptyNoteText,
}

/// Why a commit could not be read back.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FactError {
    TooLarge {
        seq: Seq,
        len: usize,
    },
    Malformed {
        seq: Seq,
        what: Malformation,
    },
    /// The commit's own `seq` is not the row it was stored under.
    SeqMismatch {
        key: Seq,
        found: u64,
    },
    NewerFormat {
        seq: Seq,
        what: Newer,
    },
}

impl FactError {
    /// The stable error code (`core-protocol.md`, § Errors).
    pub fn code(&self) -> &'static str {
        match self {
            FactError::NewerFormat { .. } => "store.newer_format",
            FactError::TooLarge { .. }
            | FactError::Malformed { .. }
            | FactError::SeqMismatch { .. } => "store.malformed_commit",
        }
    }
}

/// Why a commit could not be written.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum EncodeError {
    TooLarge { len: usize },
}

/// Encode a commit. Every fact is written at its kind's current version.
pub fn encode_commit(commit: &Commit) -> Result<Vec<u8>, EncodeError> {
    let message = pb::Commit {
        seq: commit.seq.get(),
        recorded_at_unix_ms: commit.recorded_at_ms,
        origin: Some(pb::Origin {
            kind: Some(match commit.origin {
                Origin::Command { request_id } => pb::origin::Kind::CommandRequestId(request_id),
                Origin::Job { job_id } => pb::origin::Kind::JobId(job_id),
                Origin::Maintenance => pb::origin::Kind::Maintenance(pb::Maintenance {}),
            }),
        }),
        facts: commit.facts.as_slice().iter().map(encode_fact).collect(),
    };
    let bytes = message.encode_to_vec();
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(EncodeError::TooLarge { len: bytes.len() });
    }
    Ok(bytes)
}

fn encode_fact(fact: &Fact) -> pb::Fact {
    let (kind, payload) = match &fact.body {
        FactBody::ProfileCreated {
            display_name,
            account,
        } => (
            pb::FactKind::ProfileCreated,
            pb::ProfileCreated {
                display_name: display_name.clone(),
                observed_account_id: account.as_ref().map(|a| a.as_str().to_owned()),
            }
            .encode_to_vec(),
        ),
        FactBody::ProfileRenamed { display_name } => (
            pb::FactKind::ProfileRenamed,
            pb::ProfileRenamed {
                display_name: display_name.clone(),
            }
            .encode_to_vec(),
        ),
        FactBody::ProfileRetired => (
            pb::FactKind::ProfileRetired,
            pb::ProfileRetired {}.encode_to_vec(),
        ),
        FactBody::ProfileRestored => (
            pb::FactKind::ProfileRestored,
            pb::ProfileRestored {}.encode_to_vec(),
        ),
        FactBody::SnapshotAcquired(a) => (
            pb::FactKind::SnapshotAcquired,
            encode_acquisition(a).encode_to_vec(),
        ),
        FactBody::SnapshotRetracted { digest, reason } => (
            pb::FactKind::SnapshotRetracted,
            pb::SnapshotRetracted {
                digest: digest.0.to_vec(),
                reason: reason.clone(),
            }
            .encode_to_vec(),
        ),
        FactBody::SoulMarked { soul, mark } => (
            pb::FactKind::SoulMarked,
            pb::SoulMarked {
                soul_id: soul.as_str().to_owned(),
                mark: match mark {
                    None => pb::Mark::None,
                    Some(Mark::Keep) => pb::Mark::Keep,
                    Some(Mark::Discard) => pb::Mark::Discard,
                    Some(Mark::Strengthen) => pb::Mark::Strengthen,
                }
                .into(),
            }
            .encode_to_vec(),
        ),
        FactBody::SoulNoted { soul, note } => (
            pb::FactKind::SoulNoted,
            pb::SoulNotedV2 {
                soul_id: soul.as_str().to_owned(),
                note: Some(match note {
                    Some(text) => pb::soul_noted_v2::Note::Text(text.as_str().to_owned()),
                    None => pb::soul_noted_v2::Note::Cleared(pb::NoteCleared {}),
                }),
            }
            .encode_to_vec(),
        ),
    };
    pb::Fact {
        profile: fact.profile.0.to_vec(),
        kind: kind.into(),
        version: current_version(kind),
        payload,
    }
}

fn encode_acquisition(a: &Acquisition) -> pb::SnapshotAcquired {
    pb::SnapshotAcquired {
        digest: a.digest.0.to_vec(),
        scope: match a.scope {
            Scope::Souls => pb::Scope::Souls,
        }
        .into(),
        coverage: match a.coverage {
            Coverage::Complete => pb::Coverage::Complete,
            Coverage::Partial => pb::Coverage::Partial,
        }
        .into(),
        channel: match a.channel {
            Channel::DesktopMemory => pb::Channel::DesktopMemory,
            Channel::MumuAdb => pb::Channel::MumuAdb,
        }
        .into(),
        source: match a.source {
            Source::Live => pb::Source::Live,
            Source::ExportFile => pb::Source::ExportFile,
        }
        .into(),
        probe_build_id: a.probe_build_id.clone(),
        probe_protocol_major: a.probe_version.major,
        probe_protocol_minor: a.probe_version.minor,
        observed_account_id: a.observed_account.as_ref().map(|id| id.as_str().to_owned()),
    }
}

/// Decode the commit stored under `key`, lifting every fact to its current form.
pub fn decode_commit(key: Seq, bytes: &[u8]) -> Result<Commit, FactError> {
    if bytes.len() > MAX_COMMIT_LEN {
        return Err(FactError::TooLarge {
            seq: key,
            len: bytes.len(),
        });
    }
    let malformed = |what| FactError::Malformed { seq: key, what };
    let message = pb::Commit::decode(bytes).map_err(|_| malformed(Malformation::NotACommit))?;
    if message.seq != key.get() {
        return Err(FactError::SeqMismatch {
            key,
            found: message.seq,
        });
    }
    let origin = match message.origin.and_then(|o| o.kind) {
        Some(pb::origin::Kind::CommandRequestId(request_id)) => Origin::Command { request_id },
        Some(pb::origin::Kind::JobId(job_id)) => Origin::Job { job_id },
        Some(pb::origin::Kind::Maintenance(_)) => Origin::Maintenance,
        None => return Err(malformed(Malformation::NoOrigin)),
    };
    let facts = message
        .facts
        .iter()
        .map(|f| decode_fact(key, f))
        .collect::<Result<Vec<_>, _>>()?;
    Ok(Commit {
        seq: key,
        recorded_at_ms: message.recorded_at_unix_ms,
        origin,
        facts: Facts::new(facts).ok_or(malformed(Malformation::NoFacts))?,
    })
}

fn decode_fact(seq: Seq, fact: &pb::Fact) -> Result<Fact, FactError> {
    let malformed = |what| FactError::Malformed { seq, what };
    let profile = <[u8; 16]>::try_from(fact.profile.as_slice())
        .map(ProfileId)
        .map_err(|_| malformed(Malformation::ProfileIdLength))?;
    let kind = pb::FactKind::try_from(fact.kind).map_err(|_| FactError::NewerFormat {
        seq,
        what: Newer::Kind(fact.kind),
    })?;
    if kind == pb::FactKind::Unspecified {
        return Err(malformed(Malformation::KindUnspecified));
    }
    if fact.version == 0 {
        return Err(malformed(Malformation::VersionZero));
    }
    if fact.version > current_version(kind) {
        return Err(FactError::NewerFormat {
            seq,
            what: Newer::KindVersion {
                kind: kind.as_str_name(),
                version: fact.version,
            },
        });
    }
    let body = lift(seq, kind, fact.version, &fact.payload)?;
    Ok(Fact { profile, body })
}

/// `lift : (kind, version, payload) → current payload of that kind` (`fact-format.md`). A step
/// is never deleted, because facts are never rewritten and an old fact may be in any store
/// forever. The steps so far: `SoulNoted` v1 → v2, where v1's empty text meant "cleared".
fn lift(seq: Seq, kind: pb::FactKind, version: u32, payload: &[u8]) -> Result<FactBody, FactError> {
    let malformed = |what| FactError::Malformed { seq, what };
    let bad = |_| malformed(Malformation::PayloadUndecodable);
    Ok(match (kind, version) {
        (pb::FactKind::ProfileCreated, _) => {
            let p = pb::ProfileCreated::decode(payload).map_err(bad)?;
            FactBody::ProfileCreated {
                display_name: p.display_name,
                account: account(seq, p.observed_account_id)?,
            }
        }
        (pb::FactKind::ProfileRenamed, _) => {
            let p = pb::ProfileRenamed::decode(payload).map_err(bad)?;
            FactBody::ProfileRenamed {
                display_name: p.display_name,
            }
        }
        (pb::FactKind::ProfileRetired, _) => {
            pb::ProfileRetired::decode(payload).map_err(bad)?;
            FactBody::ProfileRetired
        }
        (pb::FactKind::ProfileRestored, _) => {
            pb::ProfileRestored::decode(payload).map_err(bad)?;
            FactBody::ProfileRestored
        }
        (pb::FactKind::SnapshotAcquired, _) => {
            let p = pb::SnapshotAcquired::decode(payload).map_err(bad)?;
            FactBody::SnapshotAcquired(decode_acquisition(seq, p)?)
        }
        (pb::FactKind::SnapshotRetracted, _) => {
            let p = pb::SnapshotRetracted::decode(payload).map_err(bad)?;
            FactBody::SnapshotRetracted {
                digest: digest(seq, &p.digest)?,
                reason: p.reason,
            }
        }
        (pb::FactKind::SoulMarked, _) => {
            let p = pb::SoulMarked::decode(payload).map_err(bad)?;
            let mark = match known::<pb::Mark>(seq, "mark", p.mark)? {
                pb::Mark::None => None,
                pb::Mark::Keep => Some(Mark::Keep),
                pb::Mark::Discard => Some(Mark::Discard),
                pb::Mark::Strengthen => Some(Mark::Strengthen),
                pb::Mark::Unspecified => return Err(malformed(Malformation::Unspecified("mark"))),
            };
            FactBody::SoulMarked {
                soul: soul(seq, p.soul_id)?,
                mark,
            }
        }
        (pb::FactKind::SoulNoted, 1) => {
            let p = pb::SoulNoted::decode(payload).map_err(bad)?;
            FactBody::SoulNoted {
                soul: soul(seq, p.soul_id)?,
                // The lift step: version 1 cleared a note with the empty text.
                note: NoteText::new(p.text),
            }
        }
        (pb::FactKind::SoulNoted, _) => {
            let p = pb::SoulNotedV2::decode(payload).map_err(bad)?;
            let note = match p.note {
                Some(pb::soul_noted_v2::Note::Text(text)) => {
                    Some(NoteText::new(text).ok_or(malformed(Malformation::EmptyNoteText))?)
                }
                Some(pb::soul_noted_v2::Note::Cleared(_)) => None,
                None => return Err(malformed(Malformation::NoteUnset)),
            };
            FactBody::SoulNoted {
                soul: soul(seq, p.soul_id)?,
                note,
            }
        }
        (pb::FactKind::Unspecified, _) => return Err(malformed(Malformation::KindUnspecified)),
    })
}

fn decode_acquisition(seq: Seq, p: pb::SnapshotAcquired) -> Result<Acquisition, FactError> {
    let unspecified = |field| FactError::Malformed {
        seq,
        what: Malformation::Unspecified(field),
    };
    Ok(Acquisition {
        digest: digest(seq, &p.digest)?,
        scope: match known::<pb::Scope>(seq, "scope", p.scope)? {
            pb::Scope::Souls => Scope::Souls,
            pb::Scope::Unspecified => return Err(unspecified("scope")),
        },
        coverage: match known::<pb::Coverage>(seq, "coverage", p.coverage)? {
            pb::Coverage::Complete => Coverage::Complete,
            pb::Coverage::Partial => Coverage::Partial,
            pb::Coverage::Unspecified => return Err(unspecified("coverage")),
        },
        channel: match known::<pb::Channel>(seq, "channel", p.channel)? {
            pb::Channel::DesktopMemory => Channel::DesktopMemory,
            pb::Channel::MumuAdb => Channel::MumuAdb,
            pb::Channel::Unspecified => return Err(unspecified("channel")),
        },
        source: match known::<pb::Source>(seq, "source", p.source)? {
            pb::Source::Live => Source::Live,
            pb::Source::ExportFile => Source::ExportFile,
            pb::Source::Unspecified => return Err(unspecified("source")),
        },
        probe_build_id: p.probe_build_id,
        probe_version: ProbeVersion {
            major: p.probe_protocol_major,
            minor: p.probe_protocol_minor,
        },
        observed_account: account(seq, p.observed_account_id)?,
    })
}

fn known<E: TryFrom<i32>>(seq: Seq, field: &'static str, value: i32) -> Result<E, FactError> {
    E::try_from(value).map_err(|_| FactError::NewerFormat {
        seq,
        what: Newer::EnumValue { field, value },
    })
}

fn digest(seq: Seq, bytes: &[u8]) -> Result<Digest, FactError> {
    <[u8; 32]>::try_from(bytes)
        .map(Digest)
        .map_err(|_| FactError::Malformed {
            seq,
            what: Malformation::DigestLength,
        })
}

fn soul(seq: Seq, id: String) -> Result<GameSoulId, FactError> {
    GameSoulId::new(id).map_err(|_| FactError::Malformed {
        seq,
        what: Malformation::EmptySoulId,
    })
}

fn account(seq: Seq, id: Option<String>) -> Result<Option<GameAccountId>, FactError> {
    id.map(GameAccountId::new)
        .transpose()
        .map_err(|_| FactError::Malformed {
            seq,
            what: Malformation::EmptyAccountId,
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    const P: ProfileId = ProfileId([0xAB; 16]);

    fn seq(n: u64) -> Seq {
        Seq::new(n).expect("a seq")
    }

    fn every_kind() -> Commit {
        let soul = GameSoulId::new("s-1").expect("non-empty");
        let facts = vec![
            FactBody::ProfileCreated {
                display_name: "主号".into(),
                account: Some(GameAccountId::new("acct").expect("non-empty")),
            },
            FactBody::ProfileRenamed {
                display_name: "alt".into(),
            },
            FactBody::ProfileRetired,
            FactBody::ProfileRestored,
            FactBody::SnapshotAcquired(Acquisition {
                digest: Digest([7; 32]),
                scope: Scope::Souls,
                coverage: Coverage::Partial,
                channel: Channel::DesktopMemory,
                source: Source::Live,
                probe_build_id: "probe-1".into(),
                probe_version: ProbeVersion { major: 1, minor: 2 },
                observed_account: None,
            }),
            FactBody::SnapshotRetracted {
                digest: Digest([7; 32]),
                reason: "wrong account".into(),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: Some(Mark::Strengthen),
            },
            FactBody::SoulMarked {
                soul: soul.clone(),
                mark: None,
            },
            FactBody::SoulNoted {
                soul: soul.clone(),
                note: NoteText::new("双速"),
            },
            FactBody::SoulNoted { soul, note: None },
        ];
        Commit {
            seq: seq(3),
            recorded_at_ms: -5,
            origin: Origin::Job { job_id: 9 },
            facts: Facts::new(
                facts
                    .into_iter()
                    .map(|body| Fact { profile: P, body })
                    .collect(),
            )
            .expect("facts"),
        }
    }

    fn raw(commit: &Commit) -> pb::Commit {
        pb::Commit::decode(encode_commit(commit).expect("encodes").as_slice()).expect("decodes")
    }

    fn with_fact(f: impl FnOnce(&mut pb::Fact)) -> Vec<u8> {
        let mut c = raw(&every_kind());
        f(&mut c.facts[0]);
        c.encode_to_vec()
    }

    fn malformed(what: Malformation) -> Result<Commit, FactError> {
        Err(FactError::Malformed { seq: seq(3), what })
    }

    #[test]
    fn every_kind_round_trips() {
        let c = every_kind();
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(decode_commit(seq(3), &bytes), Ok(c));
    }

    #[test]
    fn every_origin_round_trips() {
        for origin in [
            Origin::Command { request_id: 1 },
            Origin::Job { job_id: 2 },
            Origin::Maintenance,
        ] {
            let c = Commit {
                origin,
                ..every_kind()
            };
            let bytes = encode_commit(&c).expect("encodes");
            assert_eq!(decode_commit(seq(3), &bytes).map(|d| d.origin), Ok(origin));
        }
    }

    #[test]
    fn encoding_is_deterministic_and_pinned() {
        let c = Commit {
            seq: seq(1),
            recorded_at_ms: 0,
            origin: Origin::Command { request_id: 1 },
            facts: Facts::one(Fact {
                profile: ProfileId([0; 16]),
                body: FactBody::SoulMarked {
                    soul: GameSoulId::new("a").expect("non-empty"),
                    mark: Some(Mark::Keep),
                },
            }),
        };
        let bytes = encode_commit(&c).expect("encodes");
        assert_eq!(encode_commit(&c), Ok(bytes.clone()));
        let decoded = decode_commit(seq(1), &bytes).expect("decodes");
        assert_eq!(encode_commit(&decoded), Ok(bytes.clone()));
        // These bytes are what every store holds for this commit; a change here breaks stores.
        let pinned: &[u8] = &[
            0x08, 0x01, // seq 1
            0x1A, 0x02, 0x08, 0x01, // origin: command request id 1
            0x22, 0x1D, // fact, 29 bytes
            0x0A, 0x10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, // profile
            0x10, 0x07, // kind SoulMarked
            0x18, 0x01, // version 1
            0x22, 0x05, 0x0A, 0x01, b'a', 0x10, 0x02, // payload: soul "a", mark Keep
        ];
        assert_eq!(bytes, pinned);
    }

    #[test]
    fn a_version_one_note_lifts_its_empty_text_to_cleared() {
        let v1 = |text: &str| {
            with_fact(|f| {
                f.kind = pb::FactKind::SoulNoted.into();
                f.version = 1;
                f.payload = pb::SoulNoted {
                    soul_id: "s".into(),
                    text: text.into(),
                }
                .encode_to_vec();
            })
        };
        let note = |bytes: Vec<u8>| match decode_commit(seq(3), &bytes)
            .map(|c| c.facts.into_vec().remove(0).body)
        {
            Ok(FactBody::SoulNoted { note, .. }) => note,
            other => panic!("{other:?}"),
        };
        assert_eq!(note(v1("")), None);
        assert_eq!(note(v1("keep")), NoteText::new("keep"));
    }

    #[test]
    fn a_note_is_written_at_version_two_with_its_case() {
        let c = raw(&every_kind());
        let (text, cleared) = (&c.facts[8], &c.facts[9]);
        assert_eq!((text.version, cleared.version), (2, 2));
        assert_eq!(
            pb::SoulNotedV2::decode(cleared.payload.as_slice()).map(|p| p.note),
            Ok(Some(pb::soul_noted_v2::Note::Cleared(pb::NoteCleared {})))
        );
    }

    #[test]
    fn a_version_two_note_must_say_which_case_it_is() {
        let v2 = |note| {
            with_fact(|f| {
                f.kind = pb::FactKind::SoulNoted.into();
                f.version = 2;
                f.payload = pb::SoulNotedV2 {
                    soul_id: "s".into(),
                    note,
                }
                .encode_to_vec();
            })
        };
        assert_eq!(
            decode_commit(seq(3), &v2(None)),
            malformed(Malformation::NoteUnset)
        );
        assert_eq!(
            decode_commit(
                seq(3),
                &v2(Some(pb::soul_noted_v2::Note::Text(String::new())))
            ),
            malformed(Malformation::EmptyNoteText)
        );
    }

    #[test]
    fn bytes_that_are_not_a_commit_are_malformed() {
        assert_eq!(
            decode_commit(seq(1), &[0xFF, 0xFF, 0xFF]),
            Err(FactError::Malformed {
                seq: seq(1),
                what: Malformation::NotACommit
            })
        );
        let no_origin = pb::Commit {
            seq: 1,
            ..pb::Commit::default()
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(seq(1), &no_origin),
            Err(FactError::Malformed {
                seq: seq(1),
                what: Malformation::NoOrigin
            })
        );
        let no_facts = pb::Commit {
            facts: vec![],
            ..raw(&every_kind())
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(seq(3), &no_facts),
            malformed(Malformation::NoFacts)
        );
    }

    #[test]
    fn a_commit_must_sit_under_its_own_seq() {
        let bytes = encode_commit(&every_kind()).expect("encodes");
        assert_eq!(
            decode_commit(seq(4), &bytes),
            Err(FactError::SeqMismatch {
                key: seq(4),
                found: 3
            })
        );
    }

    #[test]
    fn decoding_is_bounded() {
        let big = vec![0u8; MAX_COMMIT_LEN + 1];
        assert_eq!(
            decode_commit(seq(1), &big),
            Err(FactError::TooLarge {
                seq: seq(1),
                len: MAX_COMMIT_LEN + 1
            })
        );
        let c = Commit {
            facts: Facts::one(Fact {
                profile: P,
                body: FactBody::SoulNoted {
                    soul: GameSoulId::new("a").expect("non-empty"),
                    note: NoteText::new("x".repeat(MAX_COMMIT_LEN)),
                },
            }),
            ..every_kind()
        };
        assert!(matches!(
            encode_commit(&c),
            Err(EncodeError::TooLarge { .. })
        ));
    }

    #[test]
    fn a_newer_kind_version_or_enum_value_is_newer_format() {
        let unknown_kind = with_fact(|f| f.kind = 99);
        assert_eq!(
            decode_commit(seq(3), &unknown_kind),
            Err(FactError::NewerFormat {
                seq: seq(3),
                what: Newer::Kind(99)
            })
        );
        let v2 = with_fact(|f| f.version = 2);
        let e = decode_commit(seq(3), &v2).expect_err("newer");
        assert_eq!(e.code(), "store.newer_format");
        assert!(matches!(
            e,
            FactError::NewerFormat {
                what: Newer::KindVersion { version: 2, .. },
                ..
            }
        ));
        let note_v3 = with_fact(|f| {
            f.kind = pb::FactKind::SoulNoted.into();
            f.version = 3;
        });
        assert!(matches!(
            decode_commit(seq(3), &note_v3),
            Err(FactError::NewerFormat {
                what: Newer::KindVersion { version: 3, .. },
                ..
            })
        ));
        let mut c = raw(&every_kind());
        c.facts[6].payload = pb::SoulMarked {
            soul_id: "s".into(),
            mark: 42,
        }
        .encode_to_vec();
        assert_eq!(
            decode_commit(seq(3), &c.encode_to_vec()),
            Err(FactError::NewerFormat {
                seq: seq(3),
                what: Newer::EnumValue {
                    field: "mark",
                    value: 42
                }
            })
        );
    }

    #[test]
    fn a_malformed_envelope_or_payload_is_refused() {
        let cases: [(Malformation, Vec<u8>); 6] = [
            (Malformation::VersionZero, with_fact(|f| f.version = 0)),
            (Malformation::KindUnspecified, with_fact(|f| f.kind = 0)),
            (
                Malformation::ProfileIdLength,
                with_fact(|f| f.profile = vec![1; 15]),
            ),
            (
                Malformation::PayloadUndecodable,
                with_fact(|f| f.payload = vec![0x0A, 0x05, b'x']),
            ),
            (
                Malformation::EmptyAccountId,
                with_fact(|f| {
                    f.payload = pb::ProfileCreated {
                        display_name: "x".into(),
                        observed_account_id: Some(String::new()),
                    }
                    .encode_to_vec();
                }),
            ),
            (
                Malformation::Unspecified("coverage"),
                with_fact(|f| {
                    f.kind = pb::FactKind::SnapshotAcquired.into();
                    f.payload = pb::SnapshotAcquired {
                        digest: vec![0; 32],
                        scope: pb::Scope::Souls.into(),
                        channel: pb::Channel::MumuAdb.into(),
                        source: pb::Source::Live.into(),
                        ..pb::SnapshotAcquired::default()
                    }
                    .encode_to_vec();
                }),
            ),
        ];
        for (what, bytes) in cases {
            let e = decode_commit(seq(3), &bytes);
            assert_eq!(e, malformed(what), "{what:?}");
            assert_eq!(
                e.map_err(|e| e.code()),
                Err("store.malformed_commit"),
                "{what:?}"
            );
        }
    }
}
