//! Generates the Rust types of the fact schema with `protox`, a pure-Rust compiler, so building
//! the daemon needs no external `protoc` (ADR-0002, § The fact schema).
//!
//! Also generates the dotted names of the core protocol's failure codes from its descriptor
//! (`core-protocol.md`, "Errors"): a code is a failure oneof's field name with its first `_` read
//! as `.`, so no Rust source spells one. `yata-protocol` is pure and writes no file, so the table
//! is generated here, where the daemon uses it.

use std::fmt::Write as _;

use prost_types::FileDescriptorSet;

/// The core messages whose `kind` oneof lists failure codes, with their Rust module names.
const FAILURE_SETS: [(&str, &str); 3] = [
    ("Error", "error"),
    ("SessionFailed", "session_failed"),
    ("ClientFailure", "client_failure"),
];

const CORE: &str = "../yata-protocol/proto/core.proto";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let schemas = ["proto/fact.proto"];
    for s in schemas.iter().chain([&CORE]) {
        println!("cargo:rerun-if-changed={s}");
    }
    let descriptors = protox::compile(schemas, ["proto"])?;
    prost_build::Config::new().compile_fds(descriptors)?;
    let core = protox::compile([CORE], ["../yata-protocol/proto"])?;
    let out = std::env::var("OUT_DIR")?;
    std::fs::write(format!("{out}/core_codes.rs"), failure_codes(&core)?)?;
    Ok(())
}

/// `impl Code for pb::<set>::Kind`, one arm per oneof field, for each failure set.
fn failure_codes(set: &FileDescriptorSet) -> Result<String, Box<dyn std::error::Error>> {
    let core = set
        .file
        .iter()
        .find(|f| f.package() == "yata.core.v1")
        .ok_or("core.proto has no package yata.core.v1")?;
    let mut out = String::from(
        "// Generated by build.rs from core.proto's failure oneofs.
",
    );
    for (message, module) in FAILURE_SETS {
        let m = core
            .message_type
            .iter()
            .find(|m| m.name() == message)
            .ok_or_else(|| format!("core.proto has no message {message}"))?;
        let kind = m
            .oneof_decl
            .iter()
            .position(|o| o.name() == "kind")
            .ok_or_else(|| format!("{message} has no oneof kind"))?;
        writeln!(out, "impl Code for pb::{module}::Kind {{")?;
        writeln!(out, "    fn code(&self) -> &'static str {{")?;
        writeln!(out, "        match self {{")?;
        for field in m
            .field
            .iter()
            .filter(|f| f.oneof_index == Some(kind as i32))
        {
            let name = field.name();
            let dotted = name
                .split_once('_')
                .map(|(ns, rest)| format!("{ns}.{rest}"))
                .ok_or_else(|| format!("{message}.{name} has no namespace"))?;
            let variant = upper_camel(name);
            writeln!(
                out,
                "            pb::{module}::Kind::{variant}(_) => \"{dotted}\","
            )?;
        }
        writeln!(
            out,
            "        }}
    }}
}}"
        )?;
    }
    Ok(out)
}

/// prost's variant name for a oneof field: each `_`-separated word capitalized.
fn upper_camel(snake: &str) -> String {
    snake
        .split('_')
        .map(|w| {
            let mut c = w.chars();
            c.next()
                .map(|f| f.to_ascii_uppercase().to_string() + c.as_str())
                .unwrap_or_default()
        })
        .collect()
}
