//! Yata's wire, shared by the daemon and `yata-reader` (ADR-0004, ADR-0006).
//!
//! - [`frame`]: the one frame codec both channels use, as `core-protocol.md`, § Frame states it.
//! - [`probe`]: the probe protocol's messages, generated from `proto/probe.proto`.
//!
//! The crate is pure and depends on no workspace crate, so the reader can depend on it without
//! compiling the domain (ADR-0005, trigger 3). It moves bytes between frames and payloads and
//! does no I/O: the daemon and the reader read and write the pipes, and feed the bytes here.

pub mod frame;

/// The probe protocol (`probe-protocol.md`), generated from `proto/probe.proto` at build time.
#[allow(
    clippy::all,
    clippy::pedantic,
    reason = "generated by prost from the schema file"
)]
pub mod probe {
    include!(concat!(env!("OUT_DIR"), "/yata.probe.v1.rs"));

    /// The probe protocol version this build speaks (`protocol-versions.md`).
    pub const VERSION: ProtocolVersion = ProtocolVersion { major: 1, minor: 0 };
}

#[cfg(test)]
mod tests {
    use prost::Message;

    use super::frame::{decode_all, encode};
    use super::probe::{
        AttributeValue, ProbeMessage, ReadResult, Scope, SoulRecord, SoulRecords,
        SubAttributeValue, probe_message::Kind, read_result::Records,
    };

    #[test]
    fn a_probe_message_survives_a_frame() {
        let soul = SoulRecord {
            soul_id: "a1".into(),
            suit_code: 30,
            star: 6,
            slot: 2,
            level: 15,
            main: Some(AttributeValue {
                attribute_code: 7,
                value: 57.0,
            }),
            subs: vec![SubAttributeValue {
                attribute_code: 7,
                value: 17.1,
                roll_count: None,
            }],
            innate: None,
            locked: true,
            discarded: false,
        };
        let message = ProbeMessage {
            kind: Some(Kind::ReadResult(ReadResult {
                request_id: 1,
                scope: Scope::Souls.into(),
                records: Some(Records::Souls(SoulRecords { souls: vec![soul] })),
                ..ReadResult::default()
            })),
        };
        let stream = encode(&message.encode_to_vec()).expect("encodable");
        let payloads = decode_all(&stream).expect("one frame");
        let [payload] = payloads.as_slice() else {
            panic!("expected one frame")
        };
        assert_eq!(ProbeMessage::decode(payload.as_slice()), Ok(message));
    }

    #[test]
    fn an_absent_roll_count_differs_from_zero_rolls() {
        let with = |roll_count| SubAttributeValue {
            attribute_code: 1,
            value: 2.4,
            roll_count,
        };
        assert_ne!(with(None).encode_to_vec(), with(Some(0)).encode_to_vec());
    }
}
